Repository NomadBlacky/digdag-plugin-datadog, pull requests merged in 2020-04, with the labels that each got.

#74 Fix mishandling of getting the application key
  src/main/scala/dev/nomadblacky/digdag/plugin/datadog/operator/APIClientFactory.scala
  src/test/scala/dev/nomadblacky/digdag/plugin/datadog/operator/APIClientFactoryTest.scala
Labels: bug

#67 Update sbt-explicit-dependencies to 0.2.13
  project/plugins.sbt
Labels: dependency-updates

#69 Update sbt to 1.3.9
  project/build.properties
Labels: dependency-updates

#71 Update sbt-scalafmt to 2.3.4
  project/plugins.sbt
Labels: dependency-updates

#68 Update sbt-sonatype to 3.9.2
  project/plugins.sbt
Labels: dependency-updates

#76 Remove Digdag CI from mergify configurations
  .mergify/config.yml
Labels: builds

#77 Update sbt to 1.3.10
  project/build.properties
Labels: dependency-updates
